apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: monitorurls-app
  name: monitorurls-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: monitorurls-app
  template:
    metadata:
      labels:
        run: monitorurls-app
    spec:
      containers:
      - image: spatrayuni/monitorurls
        name: monitorurls-app
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command:
            - curl
            - http://localhost:8000/metrics
          initialDelaySeconds: 10
          periodSeconds: 3
