apiVersion: v1
kind: Service
metadata:
  name: monitorurls-app
  namespace: app
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31000
  selector:
    run: monitorurls-app
